#' Generate a chord set
#'
#' Generate a chord set for a music score.
#'
#' The chord set list returned by \code{chord_set} is only used for top center
#' placement of a full set of chord fretboard diagrams for a music score.
#' \code{chord_set} returns a named list. The names are the chords and the list
#' elements are strings defining string and fret fingering readable by LilyPond.
#' Multiple chord positions can be defined for the same chord name.
#' Instruments with a number of strings other than six are not currently
#' supported.
#'
#' When defining chords, you may also wish to define rests or silent rests for
#' chords that are to be added to a score for placement above the staff in
#' time, where no chord is to be played or explicitly written.
#' Therefore, there are occasions where you may pass chord names and positions
#' that happen to include entries \code{r} and/or \code{s} as \code{NA} as
#' shown in the example.
#' These two special cases are passed through by \code{chord_set} but are
#' ignored when the chord chart is generated.
#'
#' @param x character, n-string chord description from lowest to highest pitch,
#' strings n through 1. E.g., \code{"xo221o"}. You can use spaces or semicolons
#' when 2-digit fret numbers are present, e.g., \code{"8 10 10 9 o"}. Do not
#' mix formats. Leading \code{x} are inferred if the number of entries is less
#' than \code{n}.
#' @param id character, the name of the chord in LilyPond readable format,
#' e.g., \code{"a:m"}. Ignored if \code{x} is already a named vector.
#' @param n number of instrument strings.
#'
#' @return a named list.
#' @export
#'
#' @examples
#' chord_names <- c("e:m", "c", "d", "e:m", "d", "r", "s")
#' chord_position <- c("997x", "5553x", "7775x", "ooo22o", "232oxx", NA, NA)
#' chord_set(chord_position, chord_names)
chord_set <- function(x, id = NULL, n = 6){
  if(!is.null(names(x))) id <- names(x)
  idx <- which(is.na(x))
  if(length(idx)){
    x2 <- x[idx]
    names(x2) <- id[idx]
  }
  x <- x[!is.na(x)]
  id <- id[!id %in% c("r", "s")]
  f <- function(x){
    if(grepl(";", x)){
      if(!grepl(";$")) x <- paste0(x, ";")
    } else if(grepl(" ", x)){
      x <- paste0(gsub(" ", ";", trimws(x)), ";")
    } else {
      x <- strsplit(x, "")[[1]]
      x <- paste0(paste(x, collapse = ";"), ";")
    }
    n0 <- length(strsplit(x, ";")[[1]])
    if(n0 > n)
      stop("Cannot have more fret values than number of instrument strings.",
           call. = FALSE)
    if(n0 < n) x <- paste(c(rep("x", n - n0), x), collapse = ";")
    gsub("0", "o", x)
  }
  x <- purrr::map_chr(x, f)
  names(x) <- id
  if(length(idx)) x <- c(x, x2)
  x
}

#' Create a music track
#'
#' Create a music track from a collection of musical phrases.
#'
#' Musical phrases generated by \code{\link{phrase}} are fortified in a track
#' table. All tracks are stored as track tables, one per row, even if that
#' table consists of a single track.
#' \code{track} creates a single-entry track table.
#' See \code{\link{trackbind}} for merging single tracks into a multi-track
#' table. This is row binding that also properly preserves phrase and track
#' classes.
#'
#' The default for an additional music staff is \code{"treble_8"} for 8va
#' treble clef, which is commonly displayed in guitar tablature above
#' the tablature staff to include precise rhythm and timing information.
#' Note that guitar is a transposing instrument. For this reason, the default
#' ID is \code{"treble_8"}, not \code{"treble"}. However, there are other
#' \code{track_*} functions that have different default arguments. See examples.
#'
#' Set \code{music_staff = NA} to suppress the additional music staff above
#' the tablature staff.
#' This is appropriate for simple patterns where there are already multiple
#' tracks and the additional space required for two staves per instrument is
#' unnecessary and wasteful.
#'
#' The arguments \code{ms_transpose} and \code{ms_key} pertain to the
#' transposition of the music staff relative to the tab staff if
#' \code{music_staff} is not \code{NA}. These arguments default to 0 and
#' \code{NA}, respectively.
#' The transposition and new key are simply stored in the \code{ms_transpose}
#' and \code{ms_key} columns in the resulting track table.
#' This information is used by \code{lilypond} or \code{tab} to transpose the
#' music staff relative to the tab staff at the time of LilyPond file
#' generation.
#' Non-zero semitone transposition works without providing an explicit new key
#' signature, but it is recommended to specify because it helps ensure the
#' correct selection of accidentals in the output.
#' As with the \code{\link{transpose}} function, you can simply specify
#' \code{key = "flat"} or \code{key = "sharp"}. The exact key signature is not
#' required; it is merely more clear and informative for the user.
#'
#' @param phrase a phrase object.
#' @param tuning character, space-delimited pitches describing the instrument
#' string tuning or a predefined tuning ID (see \code{\link{tunings}}).
#' Defaults to standard guitar tuning. Tick or integer octave numbering
#' accepted for custom tuning entries. Not relevant if tablature staff is
#' suppressed.
#' @param voice integer, ID indicating the unique voice \code{phrase} belongs
#' to within a single track (another track may share the same tab/music staff
#' but have a different voice ID).
#' @param music_staff add a standard sheet music staff above the tablature
#' staff. See details.
#' @param ms_transpose integer, positive or negative number of semitones to
#' transpose an included music staff relative to the tablature staff.
#' See details.
#' @param ms_key character, specify the new key signature for a transposed music
#' staff. See details.
#' @param no_tab logical, suppress the default guitar tablature so that only a
#' standard music staff is associated with the track. Ignored if
#' \code{music_staff = NA}.
#'
#' @return a track table.
#' @export
#'
#' @examples
#' x <- phrase("c ec'g' ec'g'", "4 4 2", "5 4 4")
#' track(x) # same as track_guitar(x); 8va treble clef above tab staff
#' track_tc(x) # treble clef sheet music, no tab staff
#' track_bc(x) # bass clef sheet music, no tab staff
#'
#' x <- phrase("c, g,c g,c", "4 4 2", "3 2 2")
#' track_bass(x) # includes tab staff and standard bass tuning
track <- function(phrase, tuning = "standard", voice = 1L,
                  music_staff = "treble_8", ms_transpose = 0, ms_key = NA,
                  no_tab = FALSE){
  if(!"phrase" %in% class(phrase))
    stop("`phrase` is not a phrase object.", call. = FALSE)
  if(is.na(music_staff) & no_tab)
    stop("Cannot have both `music_staff` = NA and `no_tab` = TRUE.",
         call. = FALSE)

  tuning <- .map_tuning(tuning)
  n <- length(strsplit(tuning, " ")[[1]])
  ps <- tryCatch(phrase_strings(phrase, TRUE), error = function(e) NULL)
  if(is.null(ps)){
    p2 <- gsub("\\\\repeat (unfold|percent|volta) \\d+ \\{ | \\}|\n", "",
               phrase)
    p2 <- gsub("\\\\tuplet \\d+/\\d+ \\d+ \\{ | \\}|\n", "",
               phrase)
    ps <- tryCatch(phrase_strings(p2, TRUE), error = function(e) NULL)
  }
  if(!is.null(ps)){
    s <- as.integer(strsplit(gsub(" |NA", "", ps), "")[[1]])
    if(any(!is.na(s))){
      if(any(s > n))
        stop("String number exceeds number of strings from `tuning`.",
             call. = FALSE)
    }
  }

  x <- tibble::tibble(
    phrase, tuning = tuning, voice = as.integer(voice),
    staff = as.character(music_staff), ms_transpose = as.integer(ms_transpose),
    ms_key = as.character(ms_key), tab = !no_tab)
  x$phrase <- purrr::map(x$phrase, ~as_phrase(.x))
  class(x) <- unique(c("track", class(x)))
  x
}

#' @export
#' @rdname track
track_guitar <- track

#' @export
#' @rdname track
track_tc <- function(phrase, voice = 1L, ms_transpose = 0, ms_key = NA){
  track(phrase, "standard", voice, "treble", ms_transpose, ms_key, TRUE)
}

#' @export
#' @rdname track
track_bc <- function(phrase, voice = 1L, ms_transpose = 0, ms_key = NA){
  track(phrase, "standard", voice, "bass", ms_transpose, ms_key, TRUE)
}

#' @export
#' @rdname track
track_bass <- function(phrase, voice = 1L, ms_transpose = 0, ms_key = NA){
  track(phrase, "bass", voice, "bass_8", ms_transpose, ms_key, FALSE)
}

#' Bind track tables
#'
#' Bind together track tables by row.
#'
#' This function appends multiple track tables into a single track table for
#' preparation of generating a multi-track score.
#' \code{tabstaff} is used to separate music staves in the sheet
#' music/tablature output. A track's \code{voice} is used to separate distinct
#' voices within a common music staff.
#'
#' If not provided, the \code{tabstaff} ID automatically propagates \code{1:n}
#' for \code{n} tracks passed to \code{...} when binding these tracks together.
#' This expresses the default assumption of one tab staff per track.
#' This is the typical use case where each single \code{track} object being
#' bound into a multi-\code{track} object is a fully separated track on its own
#' staff.
#'
#' However, some tracks represent different voices that share the same staff.
#' These should be assigned the same staff ID value, in which case you must
#' provide the \code{tabstaff} argument.
#' An error will be thrown if any two tracks have both the same \code{voice}
#' and the same \code{tabstaff}. The pair must be unique. E.g.,
#' provide \code{tabstaff = c(1, 1)} when you have two tracks with \code{voice}
#' equal to 1 and 2. See examples.
#'
#' Note that the actual ID values assigned to each track do not matter;
#' only the order in which tracks are bound, first to last.
#'
#' @param ... track tables.
#' @param tabstaff integer, ID vector indicating the tablature staff for each
#' track. See details.
#'
#' @return a track table.
#' @export
#'
#' @examples
#' x <- phrase("c ec'g' ec'g'", "4 4 2", "5 432 432")
#' x1 <- track(x)
#' x2 <- track(x, voice = 2)
#' trackbind(x1, x1)
#' trackbind(x1, x2, tabstaff = c(1, 1))
trackbind <- function(..., tabstaff){
  x <- list(...)
  if(!all(purrr::map_lgl(x, ~any(class(.x) == "track"))))
    stop("All arguments must be `track` tables.", call. = FALSE)
  y <- if(missing(tabstaff)) seq_along(x) else tabstaff
  x <- purrr::map2(x, y, ~dplyr::mutate(.x, tabstaff = as.integer(.y)))
  x <- suppressWarnings(dplyr::bind_rows(x))
  if(nrow(dplyr::distinct(x, .data[["voice"]], .data[["tabstaff"]])) < nrow(x))
    stop(paste("track `voice` and `tabstaff` ID combination must be unique",
               "across track rows."), call. = FALSE)
  x$phrase <- purrr::map(x$phrase, ~as_phrase(.x))
  class(x) <- unique(c("track", class(x)))
  x
}

#' Create a music score
#'
#' Create a music score from a collection of tracks.
#'
#' Score takes track tables generated by \code{\link{track}} and fortifies them
#' as a music score. It optionally binds tracks with a set of chord diagrams.
#' There may be only one track in \code{track} as well as no chord information
#' passed, but for consistency \code{score} is still required to fortify the
#' single track as a score object that can be rendered by \code{\link{tab}}.
#'
#' @param track a track table consisting of one or more tracks.
#' @param chords an optional named list of chords and respective fingerings
#' generated by \code{chord_set}, for inclusion of a top center chord diagram
#' chart.
#' @param chord_seq an optional named vector of chords and their durations, for
#' placing chord diagrams above staves in time.
#'
#' @return a score table.
#' @export
#'
#' @examples
#' x <- phrase("c ec'g' ec'g'", "4 4 2", "5 432 432")
#' x <- track(x)
#' score(x)
score <- function(track, chords = NULL, chord_seq = NULL){
  cl <- class(track)
  if(!"track" %in% cl) stop("`track` is not a `track` table.", call. = FALSE)
  if(!"tabstaff" %in% names(track)) track <- dplyr::mutate(track, tabstaff = 1L)
  class(track) <- unique(c("score", cl))
  attr(track, "chords") <- chords
  attr(track, "chord_seq") <- chord_seq
  track
}
